# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title: "CariDiScho"
year: "2021"
description: "A Directory of Caribbean Digital Scholarship"
url: ""
baseurl: "/caridischo"
copyright: "CC-BY 4.0 International"
logo: "/img/logo.png"

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

# permalink: "pretty"
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
  - wax_theme
  - package.json
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  main: # name of collection
    output: true # makes sure pages are output as html files
    layout: "caridischo_item" # the layout for the pages to use
    metadata:
      source: "2021.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/caridischo" # path to the directory of images within `_data`
  test: # name of collection
    output: true # makes sure pages are output as html files
    layout: "test" # the layout for the pages to use
    metadata:
      source: "test.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/test" # path to the directory of images within `_data`
# --------------------------------------------------------------
# LUNR SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple lunr indexes below (though only one is
# recommended!) by specifying
# a `file` to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:lunr` .
# You can optionally generate a default UI by specifying a UI file
# and running `$ bundle exec rake wax:lunr UI=true`.

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      main:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - blurb
          - caridischo_genre
          - claimed_genre
          - language
          - creators
          - stewards

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  en:
    - label: "Browse"
      sub:
        - label: "Collections & Curations"
          link: "/collections/"
        - label: "Maps & Visualizations"
          link: "/visualizations/"
        - label: "Periodicals & Blogs"
          link: "/publications/"
        - label: "Reference Works"
          link: "/reference/"
        - label: "Cabinet of Wonders"
          link: "/wonders/"
    - label: "Search"
      link: "/search/"
    - label: "About"
      sub:
        - label: "Sources"
          link: "/reuse/"
        - label: "Credits"
          link: "/credits/"
        - label: "FAQ"
          link: "/faq/"
  es:
    - label: "Navegar"
      sub:
        - label: "Colecciones"
          link: "/collections/"
        - label: "Mapas & Visualizaciones"
          link: "/visualizations/"
        - label: "Publicaciones"
          link: "/publications/"
        - label: "Referencia"
          link: "/reference/"
        - label: "Gabinete de maravillas"
          link: "/wonders/"
    - label: "Busqueda"
      link: "/search/"
    - label: "Acerca de"
      sub:
        - label: "Fuentes"
          link: "/reuse/"
        - label: "Creditos"
          link: "/credits/"
        - label: "Preguntas frecuentes"
          link: "/faq/"

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: "GitHub"
      link: "https://github.com/elotroalex/caridischo"
    - label: "Contact"
      link: "mailto:agil@columbia.edu"
  logos:
    - img: "/img/logo.png"
    - img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2r40VYrf2Q5jkJiPGjPkl7xZoHJliwgVtHCLVXmAsRKw0ZudD"
      link: "https://library.columbia.edu"

# --------------------------------------------------------------
# POLYGLOT I18N LOCALIZATION
# https://github.com/untra/polyglot
# --------------------------------------------------------------
#

plugins:
  - jekyll-polyglot

languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["img", "assets"]
parallel_localization: true

sass:
    sourcemap: never


# FIN
