# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title: "CariDiScho"
year: "2021"
description: "A Directory of Caribbean Digital Scholarship"
url: "https://caribbeandigitalnyc.net"
baseurl: "/caridischo"
logo: "/img/logo.png"

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: "pretty"
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
  - wax_theme
  - package.json
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  main: 
    output: true 
    layout: "caridischo_item" 
    metadata:
      source: "2021.csv" 
    images:
      source: "raw_images/caridischo" 
  curations: 
    output: true 
    layout: "caridischo_item" 
    metadata:
      source: "curations.csv" 
    images:
      source: "raw_images/curations" 
  wonders: 
    output: true 
    layout: "caridischo_item" 
    metadata:
      source: "wonders.csv" 
    images:
      source: "raw_images/wonders" 
  visualizations: 
    output: true 
    layout: "caridischo_item" 
    metadata:
      source: "visualizations.csv" 
    images:
      source: "raw_images/visualizations" 
  publications: 
    output: true 
    layout: "caridischo_item" 
    metadata:
      source: "publications.csv" 
    images:
      source: "raw_images/publications" 
  reference: 
    output: true 
    layout: "caridischo_item" 
    metadata:
      source: "reference.csv" 
    images:
      source: "raw_images/reference"

# --------------------------------------------------------------
# LUNR SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple lunr indexes below (though only one is
# recommended!) by specifying
# a `file` to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:lunr` .
# You can optionally generate a default UI by specifying a UI file
# and running `$ bundle exec rake wax:lunr UI=true`.

search:
  main:
    index: "/search/index.json" 
    collections:
      curations:
        content: false 
        fields: 
          - label
          - label_en
          - label_es
          - blurb_en
          - blurb_es
          - claimed_genre_en
          - claimed_genre_es
          - language
          - creators
          - stewards
      wonders:
        content: false 
        fields: 
          - label
          - label_en
          - label_es
          - blurb_en
          - blurb_es
          - claimed_genre_en
          - claimed_genre_es
          - language
          - creators
          - stewards
      visualizations:
        content: false 
        fields: 
          - label
          - label_en
          - label_es
          - blurb_en
          - blurb_es
          - claimed_genre_en
          - claimed_genre_es
          - language
          - creators
          - stewards
      publications:
        content: false 
        fields: 
          - label
          - label_en
          - label_es
          - blurb_en
          - blurb_es
          - claimed_genre_en
          - claimed_genre_es
          - language
          - creators
          - stewards
      reference:
        content: false 
        fields: 
          - label
          - label_en
          - label_es
          - blurb_en
          - blurb_es
          - claimed_genre_en
          - claimed_genre_es
          - language
          - creators
          - stewards



# --------------------------------------------------------------
# POLYGLOT I18N LOCALIZATION
# https://github.com/untra/polyglot
# --------------------------------------------------------------
#

plugins:
  - jekyll-polyglot

languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["img", "assets"]
parallel_localization: true

sass:
    sourcemap: never


# FIN
