# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title: "CariDiScho"
year: "2021"
description: "A Directory of Caribbean Digital Scholarship"
url: ""
baseurl: "/caridischo"
copyright: "CC-BY 4.0 International"
logo: "/img/logo.png"

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

# permalink: "pretty"
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
  - wax_theme
  - package.json
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  main: # name of collection
    output: true # makes sure pages are output as html files
    layout: "caridischo_item" # the layout for the pages to use
    metadata:
      source: "2021.csv" # path to the metadata file within `_data`
    images:
      source: "raw_images/caridischo" # path to the directory of images within `_data`

# --------------------------------------------------------------
# LUNR SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple lunr indexes below (though only one is
# recommended!) by specifying
# a `file` to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:lunr` .
# You can optionally generate a default UI by specifying a UI file
# and running `$ bundle exec rake wax:lunr UI=true`.

search:
  main:
    index: "/search/index.json" # file the index will get written to
    collections:
      main:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - blurb
          - caridischo_genre
          - claimed_genre
          - language
          - creators
          - stewards




# --------------------------------------------------------------
# POLYGLOT I18N LOCALIZATION
# https://github.com/untra/polyglot
# --------------------------------------------------------------
#

plugins:
  - jekyll-polyglot

languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["img", "assets"]
parallel_localization: true

sass:
    sourcemap: never


# FIN
